### ISSUE TITLE
camunda-modeler-linter-plugin does not work with Modeler 5.3.0

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda/camunda-modeler-linter-plugin#28]
Hello,
I copied all the plugins I have from Modeler 5.2 to 5.3, and I received this error.

Thie plug in which failed is the linter:
camunda-modeler-property-info-plugin-master](https://github.com/camunda/camunda-modeler-linter-plugin)

```
[D:\dev\intellij\community\zeebe-cherry-framework\src\test\resources\connectorworker\connectorworker.bpmn] this.getModeler(...).get(...).deactivate is not a function
    at deactivate (webpack://camunda-modeler-client/src/app/tabs/cloud-bpmn/BpmnEditor.js:187:39)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:216:295)
    at Vh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:220:181)
    at file:///D:/Camunda/camunda-modeler-5.3.0/resources/app.asar/public/bundle.js:2:803376
    at b (webpack://camunda-modeler-client/node_modules/scheduler/cjs/scheduler.production.min.js:18:162)
    at unstable_runWithPriority (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:250:202)
    at Fi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:249:382)
    at Di (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:248:143)
    at Yh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:245:331)
    at Xh (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:243:85)
    at qf (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:130:227)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:13:223)
    at file:///D:/Camunda/camunda-modeler-5.3.0/resources/app.asar/public/bundle.js:2:2350775 [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
[Disable plug-ins (restarts the app)](https://github.com/camunda/camunda-modeler/issues/new?template=BUG_REPORT.md#) [ info ]
```

**Comment by pinussilvestrus** [comment]
I moved the issue to the correct repository.

**Comment by ingorichtsmeier** [comment]
Does the built in linting works for Camunda 7 and Camunda 8? 

Does the linter plugin work for both versions? 

Maybe a rename of the linter plugin helps? (linting-camunda-7)

**Comment by nikku** [comment]
We'll need to investigate how to properly integrate the plug-in in Camunda Modeler 5.3+.

**Comment by philippfromme** [comment]
This is an issue indeed. Both the linting feature in the Camunda Modeler and bpmn-js-bpmnlint add a `linting` module (cf. https://github.com/bpmn-io/bpmn-js-bpmnlint/blob/master/lib/index.js#L6). Using 
`camunda-modeler-linter-plugin` overrides the `linting` module which breaks linting. We could namespace the Camunda Modeler module with the upcoming patch release to avoid clashes. On the other hand we could also deprecate this plugin since it's basically succeeded by the buil-in linting feature. The only thing that's missing is the ability to add custom rules.

**Comment by christian-konrad** [comment]
@philippfromme @nikku @CatalinaMoisuc I propose that we spend time to support custom rules with the new built-in linter. We should support the same rule schema/API/etc as before, so no change needed for customers. When we did this, and someone using the plugin, I would expect to show a message in the log that the old plugin is deprecated now and replaced by our built-in feature. I'll create an issue for that.

At the same time, we should at least think about how to bring custom rules to Web Modeler (for example, first iteration: a declarative JSON in the Web Modeler project). 

Before that, we should at least ship a patch asap, so it won't break anymore as it does right now. Let this issue here cover that.

**Comment by philippfromme** [comment]
@christian-konrad I agree with you. I discussed this with @nikku and we came to a similar conclusion:

* the linting feature of the Camunda Modeler succeeds the linting plugin
* using the linting feature _and_ the linting plugin at the same time is not a use case we want to support
* to replace the linting plugin the linting feature in the Camunda Modeler is missing the ability to add custom rules

Therefore we should

1. Not invest into making the the linting plugin compatible with Camunda Modeler 5.3
2. Deprecate the the plugin and update it so that it notifies the user about the deprecation
3. Add the ability to the Camunda Modeler 5.3 to include custom rules

We sketched this on a Miro board: https://miro.com/app/board/uXjVPW7Ui3A=/

**Comment by nikku** [comment]
@pierre-yves-monnet @ingorichtsmeier The plug-in does not support Camunda Modeler 5.3+. We'll indicate this in the README and also look into exploding in a controlled manner (TM).

In the future we'll provide extension points to plug-in your own rules (both bpmnlint:recommended ones, but also custom ones). Leaving this issue broken to track the regression (no bpmnlint:recommended linting possible in Camunda Modeler v5.3+).

**Comment by nikku** [comment]
For your information the next modeler will provide built-in pluggable lint rules: https://github.com/camunda/camunda-modeler/pull/3153. 

We're going to proceed to deprecate this plug-in.
